### PR TITLE
Json encoding & clean Icarus simulator

### PR DESCRIPTION
**Pull request by Hugh-OBrien**
- Added clean version of Icarus simulator
- Added test scripts for converting results and icarus topology objects into json
- Added sample json for results and topology to /fixtures

### CODE REVIEW

**Comment by Hugh-OBrien** [comment]
@FilWisher @David-Loughnane  @lisanka93  @Vincent-liuwingsang  @Noppawee  

Please :+1: to approve once you're happy! ¯_(ツ)_/¯

**Comment by FilWisher** [comment]
:+1:

**Comment by Hugh-OBrien** [comment]
@FilWisher @Noppawee @David-Loughnane @lisanka93  @Vincent-liuwingsang  Can I go ahead and merge this?

**Comment by Vincent-liuwingsang** [comment]
Thumbs UP!

**Pull request merged**
